def label = "worker-${UUID.randomUUID().toString()}"

podTemplate(label: label, containers: [
    containerTemplate(name: 'maven', image: 'maven:3.6.1-jdk-11-slim', command: 'cat', ttyEnabled: true),
    containerTemplate(name: 'kaniko', image: 'kbristow/kaniko-simple:latest', command: 'cat', ttyEnabled: true),
], 
volumes: [
    persistentVolumeClaim(claimName: 'maven-cache', mountPath: '/root/.m2cache')
]){
    node(label) {
        def myRepo = checkout scm
        def gitCommit = myRepo.GIT_COMMIT
        def gitBranch = myRepo.GIT_BRANCH
        def shortGitCommit = "${gitCommit[0..10]}"

        stage('Build') {
            container('maven') {
                sh "mvn -Dmaven.repo.local=/root/.m2cache install"
            }
        }

        stage('Test') {
            container('maven') {
                sh "mvn -Dmaven.repo.local=/root/.m2cache test"
            }
        }

        stage('Package') {
            container('kaniko') {
                sh "executor --context=\$(pwd) --destination=registry.kube-system.svc.cluster.local/something:latest --dockerfile=Dockerfile"
            }
        }
    }
}
